--[[
loottables.en.lua
This file assigns a title to every loot table.  The primary use of this table
is in the search function, as when iterating through the loot tables there is no
inherant title to the loot table, given the origins of the mod as an Atlas plugin.
]]

--Invoke libraries
if (GetLocale() == "koKR") then

--Table of loot titles
--AtlasLoot_TableNames = {
	--Keys
--AtlasLoot_TableNames["VanillaKeys"][1] = "VanillaKeys";
	--Blackfathom Deeps
AtlasLoot_TableNames["BFDGhamoora"][1] = "BFDGhamoora";
AtlasLoot_TableNames["BFDLadySarevess"][1] = "BFDLadySarevess";
AtlasLoot_TableNames["BFDGelihast"][1] = "BFDGelihast";
AtlasLoot_TableNames["BFDBaronAquanis"][1] = "BFDBaronAquanis";
AtlasLoot_TableNames["BFDTwilightLordKelris"][1] = "BFDTwilightLordKelris";
AtlasLoot_TableNames["BFDOldSerrakis"][1] = "BFDOldSerrakis";
AtlasLoot_TableNames["BFDAkumai"][1] = "BFDAkumai";
AtlasLoot_TableNames["BFDTrash"][1] = "BFDTrash";
	--Blackrock Mountain
AtlasLoot_TableNames["BRMScarshieldQuartermaster"][1] = "BRMScarshieldQuartermaster";
	--Blackrock Depths
AtlasLoot_TableNames["BRDPyron"][1] = "BRDPyron";
AtlasLoot_TableNames["BRDLordRoccor"][1] = "BRDLordRoccor";
AtlasLoot_TableNames["BRDHighInterrogatorGerstahn"][1] = "BRDHighInterrogatorGerstahn";
AtlasLoot_TableNames["BRDAnubshiah"][1] = "BRDAnubshiah";
AtlasLoot_TableNames["BRDEviscerator"][1] = "BRDEviscerator";
AtlasLoot_TableNames["BRDGorosh"][1] = "BRDGorosh";
AtlasLoot_TableNames["BRDGrizzle"][1] = "BRDGrizzle";
AtlasLoot_TableNames["BRDHedrum"][1] = "BRDHedrum";
AtlasLoot_TableNames["BRDOkthor"][1] = "BRDOkthor";
AtlasLoot_TableNames["BRDTheldren"][1] = "BRDTheldren";
AtlasLoot_TableNames["BRDHoundmaster"][1] = "BRDHoundmaster";
AtlasLoot_TableNames["BRDForgewright"][1] = "BRDForgewright";
AtlasLoot_TableNames["BRDPyromancerLoregrain"][1] = "BRDPyromancerLoregrain";
AtlasLoot_TableNames["BRDTheVault"][1] = "BRDTheVault";
AtlasLoot_TableNames["BRDWarderStilgiss"][1] = "BRDWarderStilgiss";
AtlasLoot_TableNames["BRDVerek"][1] = "BRDVerek";
AtlasLoot_TableNames["BRDFineousDarkvire"][1] = "BRDFineousDarkvire";
AtlasLoot_TableNames["BRDLordIncendius"][1] = "BRDLordIncendius";
AtlasLoot_TableNames["BRDBaelGar"][1] = "BRDBaelGar";
AtlasLoot_TableNames["BRDGeneralAngerforge"][1] = "BRDGeneralAngerforge";
AtlasLoot_TableNames["BRDGolemLordArgelmach"][1] = "BRDGolemLordArgelmach";
AtlasLoot_TableNames["BRDGuzzler"][1] = "BRDGuzzler";
AtlasLoot_TableNames["BRDFlamelash"][1] = "BRDFlamelash";
AtlasLoot_TableNames["BRDPanzor"][1] = "BRDPanzor";
AtlasLoot_TableNames["BRDTomb"][1] = "BRDTomb";
AtlasLoot_TableNames["BRDLyceum"][1] = "BRDLyceum";
AtlasLoot_TableNames["BRDMagmus"][1] = "BRDMagmus";
AtlasLoot_TableNames["BRDPrincess"][1] = "BRDPrincess";
AtlasLoot_TableNames["BRDEmperorDagranThaurissan"][1] = "BRDEmperorDagranThaurissan";
AtlasLoot_TableNames["BRDBSPlans"][1] = "BRDBSPlans";
AtlasLoot_TableNames["BRDTrash"][1] = "BRDTrash";
	--Lower Blackrock Spire
AtlasLoot_TableNames["LBRSSpirestoneButcher"][1] = "LBRSSpirestoneButcher";
AtlasLoot_TableNames["LBRSPike"][1] = "LBRSPike";
AtlasLoot_TableNames["LBRSOmokk"][1] = "LBRSOmokk";
AtlasLoot_TableNames["LBRSSpirestoneBattleLord"][1] = "LBRSSpirestoneBattleLord";
AtlasLoot_TableNames["LBRSSpirestoneLordMagus"][1] = "LBRSSpirestoneLordMagus";
AtlasLoot_TableNames["LBRSVosh"][1] = "LBRSVosh";
AtlasLoot_TableNames["LBRSVoone"][1] = "LBRSVoone";
AtlasLoot_TableNames["LBRSGrayhoof"][1] = "LBRSGrayhoof";
AtlasLoot_TableNames["LBRSGrimaxe"][1] = "LBRSGrimaxe";
AtlasLoot_TableNames["LBRSSmolderweb"][1] = "LBRSSmolderweb";
AtlasLoot_TableNames["LBRSCrystalFang"][1] = "LBRSCrystalFang";
AtlasLoot_TableNames["LBRSHumanRemains"][1] = "LBRSHumanRemains";
AtlasLoot_TableNames["LBRSDoomhowl"][1] = "LBRSDoomhowl";
AtlasLoot_TableNames["LBRSZigris"][1] = "LBRSZigris";
AtlasLoot_TableNames["LBRSHalycon"][1] = "LBRSHalycon";
AtlasLoot_TableNames["LBRSSlavener"][1] = "LBRSSlavener";
AtlasLoot_TableNames["LBRSBashguud"][1] = "LBRSBashguud";
AtlasLoot_TableNames["LBRSWyrmthalak"][1] = "LBRSWyrmthalak";
AtlasLoot_TableNames["LBRSFelguard"][1] = "LBRSFelguard";
AtlasLoot_TableNames["LBRSTrash"][1] = "LBRSTrash";
	--Upper Blackrock Spire
AtlasLoot_TableNames["UBRSEmberseer"][1] = "UBRSEmberseer";
AtlasLoot_TableNames["UBRSSolakar"][1] = "UBRSSolakar";
AtlasLoot_TableNames["UBRSFlame"][1] = "UBRSFlame";
AtlasLoot_TableNames["UBRSRunewatcher"][1] = "UBRSRunewatcher";
AtlasLoot_TableNames["UBRSAnvilcrack"][1] = "UBRSAnvilcrack";
AtlasLoot_TableNames["UBRSRend"][1] = "UBRSRend";
AtlasLoot_TableNames["UBRSGyth"][1] = "UBRSGyth";
AtlasLoot_TableNames["UBRSBeast"][1] = "UBRSBeast";
AtlasLoot_TableNames["UBRSValthalak"][1] = "UBRSValthalak";
AtlasLoot_TableNames["UBRSDrakkisath"][1] = "UBRSDrakkisath";
AtlasLoot_TableNames["UBRSTrash"][1] = "UBRSTrash";
	--Blackwing Lair
AtlasLoot_TableNames["BWLRazorgore"][1] = "BWLRazorgore";
AtlasLoot_TableNames["BWLVaelastrasz"][1] = "BWLVaelastrasz";
AtlasLoot_TableNames["BWLLashlayer"][1] = "BWLLashlayer";
AtlasLoot_TableNames["BWLFiremaw"][1] = "BWLFiremaw";
AtlasLoot_TableNames["BWLEbonroc"][1] = "BWLEbonroc";
AtlasLoot_TableNames["BWLFlamegor"][1] = "BWLFlamegor";
AtlasLoot_TableNames["BWLChromaggus"][1] = "BWLChromaggus";
AtlasLoot_TableNames["BWLNefarian"][1] = "BWLNefarian";
AtlasLoot_TableNames["BWLTrashMobs"][1] = "BWLTrashMobs";
	--The Deadmines
AtlasLoot_TableNames["DMJaredVoss"][1] = "DMJaredVoss";
AtlasLoot_TableNames["DMMarisaduPaige"][1] = "DMMarisaduPaige";
AtlasLoot_TableNames["DMBrainwashedNoble"][1] = "DMBrainwashedNoble";
AtlasLoot_TableNames["DMForemanThistlenettle"][1] = "DMForemanThistlenettle";
AtlasLoot_TableNames["DMRhahkZor"][1] = "DMRhahkZor";
AtlasLoot_TableNames["DMMinerJohnson"][1] = "DMMinerJohnson";
AtlasLoot_TableNames["DMSneed"][1] = "DMSneed";
AtlasLoot_TableNames["DMSneedsShredder"][1] = "DMSneedsShredder";
AtlasLoot_TableNames["DMGilnid"][1] = "DMGilnid";
AtlasLoot_TableNames["DMHarvester"][1] = "DMHarvester";
AtlasLoot_TableNames["DMDefiasGunpowder"][1] = "DMDefiasGunpowder";
AtlasLoot_TableNames["DMMrSmite"][1] = "DMMrSmite";
AtlasLoot_TableNames["DMCookie"][1] = "DMCookie";
AtlasLoot_TableNames["DMCaptainGreenskin"][1] = "DMCaptainGreenskin";
AtlasLoot_TableNames["DMVanCleef"][1] = "DMVanCleef";
AtlasLoot_TableNames["DMTrash"][1] = "DMTrash";
	--Dire Maul East
AtlasLoot_TableNames["DMEPusillin"][1] = "DMEPusillin";
AtlasLoot_TableNames["DMEZevrimThornhoof"][1] = "DMEZevrimThornhoof";
AtlasLoot_TableNames["DMEHydro"][1] = "DMEHydro";
AtlasLoot_TableNames["DMELethtendris"][1] = "DMELethtendris";
AtlasLoot_TableNames["DMEPimgib"][1] = "DMEPimgib";
AtlasLoot_TableNames["DMEAlzzin"][1] = "DMEAlzzin";
AtlasLoot_TableNames["DMEIsalien"][1] = "DMEIsalien";
AtlasLoot_TableNames["DMETrash"][1] = "DMETrash";
AtlasLoot_TableNames["DMEShard"][1] = "DMEShard";
AtlasLoot_TableNames["DMTome"][1] = "DMTome";
AtlasLoot_TableNames["DMEBooks"][1] = "DMEBooks";
	--Dire Maul North
AtlasLoot_TableNames["DMNGuardMoldar"][1] = "DMNGuardMoldar";
AtlasLoot_TableNames["DMNStomperKreeg"][1] = "DMNStomperKreeg";
AtlasLoot_TableNames["DMNGuardFengus"][1] = "DMNGuardFengus";
AtlasLoot_TableNames["DMNThimblejack"][1] = "DMNThimblejack";
AtlasLoot_TableNames["DMNGuardSlipkik"][1] = "DMNGuardSlipkik";
AtlasLoot_TableNames["DMNCaptainKromcrush"][1] = "DMNCaptainKromcrush";
AtlasLoot_TableNames["DMNChoRush"][1] = "DMNChoRush";
AtlasLoot_TableNames["DMNKingGordok"][1] = "DMNKingGordok";
AtlasLoot_TableNames["DMNTrash"][1] = "DMNTrash";
AtlasLoot_TableNames["DMNTRIBUTERUN"][1] = "DMNTRIBUTERUN";
AtlasLoot_TableNames["DMNBooks"][1] = "DMNBooks";
	--Dire Maul West
AtlasLoot_TableNames["DMWTendrisWarpwood"][1] = "DMWTendrisWarpwood";
AtlasLoot_TableNames["DMWIllyannaRavenoak"][1] = "DMWIllyannaRavenoak";
AtlasLoot_TableNames["DMWMagisterKalendris"][1] = "DMWMagisterKalendris";
AtlasLoot_TableNames["DMWTsuzee"][1] = "DMWTsuzee";
AtlasLoot_TableNames["DMWRevanchion"][1] = "DMWRevanchion";
AtlasLoot_TableNames["DMWImmolthar"][1] = "DMWImmolthar";
AtlasLoot_TableNames["DMWHelnurath"][1] = "DMWHelnurath";
AtlasLoot_TableNames["DMWPrinceTortheldrin"][1] = "DMWPrinceTortheldrin";
AtlasLoot_TableNames["DMWShendralarProvisioner"][1] = "DMWShendralarProvisioner";
AtlasLoot_TableNames["DMWTrash"][1] = "DMWTrash";
AtlasLoot_TableNames["DMWBooks"][1] = "DMWBooks";
	--Gnomeregan
AtlasLoot_TableNames["GnNamdoBizzfizzle"][1] = "GnNamdoBizzfizzle";
AtlasLoot_TableNames["GnTechbot"][1] = "GnTechbot";
AtlasLoot_TableNames["GnGrubbis"][1] = "GnGrubbis";
AtlasLoot_TableNames["GnViscousFallout"][1] = "GnViscousFallout";
AtlasLoot_TableNames["GnElectrocutioner6000"][1] = "GnElectrocutioner6000";
AtlasLoot_TableNames["GnCrowdPummeler960"][1] = "GnCrowdPummeler960";
AtlasLoot_TableNames["GnDIAmbassador"][1] = "GnDIAmbassador";
AtlasLoot_TableNames["GnMekgineerThermaplugg"][1] = "GnMekgineerThermaplugg";
AtlasLoot_TableNames["GnTrash"][1] = "GnTrash";
AtlasLoot_TableNames["GnOutsideTrash"][1] = "GnOutsideTrash";
AtlasLoot_TableNames["GnPunchographA"][1] = "GnPunchographA";
AtlasLoot_TableNames["GnPunchographB"][1] = "GnPunchographB";
AtlasLoot_TableNames["GnPunchographC"][1] = "GnPunchographC";
AtlasLoot_TableNames["GnPunchographD"][1] = "GnPunchographD";
	--Maraudon
AtlasLoot_TableNames["MaraNamelesProphet"][1] = "MaraNamelesProphet";
AtlasLoot_TableNames["MaraKhanKolk"][1] = "MaraKhanKolk";
AtlasLoot_TableNames["MaraKhanGelk"][1] = "MaraKhanGelk";
AtlasLoot_TableNames["MaraKhanMagra"][1] = "MaraKhanMagra";
AtlasLoot_TableNames["MaraKhanVeng"][1] = "MaraKhanVeng";
AtlasLoot_TableNames["MaraNoxxion"][1] = "MaraNoxxion";
AtlasLoot_TableNames["MaraRazorlash"][1] = "MaraRazorlash";
AtlasLoot_TableNames["MaraKhanMaraudos"][1] = "MaraKhanMaraudos";
AtlasLoot_TableNames["MaraLordVyletongue"][1] = "MaraLordVyletongue";
AtlasLoot_TableNames["MaraMeshlok"][1] = "MaraMeshlok";
AtlasLoot_TableNames["MaraCelebras"][1] = "MaraCelebras";
AtlasLoot_TableNames["MaraLandslide"][1] = "MaraLandslide";
AtlasLoot_TableNames["MaraTinkererGizlock"][1] = "MaraTinkererGizlock";
AtlasLoot_TableNames["MaraRotgrip"][1] = "MaraRotgrip";
AtlasLoot_TableNames["MaraPrincessTheradras"][1] = "MaraPrincessTheradras";
AtlasLoot_TableNames["MaraTrash"][1] = "MaraTrash";
	--Molten Core
AtlasLoot_TableNames["MCLucifron"][1] = "MCLucifron";
AtlasLoot_TableNames["MCMagmadar"][1] = "MCMagmadar";
AtlasLoot_TableNames["MCGehennas"][1] = "MCGehennas";
AtlasLoot_TableNames["MCGarr"][1] = "MCGarr";
AtlasLoot_TableNames["MCShazzrah"][1] = "MCShazzrah";
AtlasLoot_TableNames["MCGeddon"][1] = "MCGeddon";
AtlasLoot_TableNames["MCGolemagg"][1] = "MCGolemagg";
AtlasLoot_TableNames["MCSulfuron"][1] = "MCSulfuron";
AtlasLoot_TableNames["MCMajordomo"][1] = "MCMajordomo";
AtlasLoot_TableNames["MCRagnaros"][1] = "MCRagnaros";
AtlasLoot_TableNames["MCRANDOMBOSSDROPS"][1] = "MCRANDOMBOSSDROPS";
AtlasLoot_TableNames["MCTrashMobs"][1] = "MCTrashMobs";
	--Naxxramas
AtlasLoot_TableNames["NAXPatchwerk"][1] = "NAXPatchwerk";
AtlasLoot_TableNames["NAXGrobbulus"][1] = "NAXGrobbulus";
AtlasLoot_TableNames["NAXGluth"][1] = "NAXGluth";
AtlasLoot_TableNames["NAXThaddius"][1] = "NAXThaddius";
AtlasLoot_TableNames["NAXAnubRekhan"][1] = "NAXAnubRekhan";
AtlasLoot_TableNames["NAXGrandWidowFaerlina"][1] = "NAXGrandWidowFaerlina";
AtlasLoot_TableNames["NAXMaexxna"][1] = "NAXMaexxna";
AtlasLoot_TableNames["NAXInstructorRazuvious"][1] = "NAXInstructorRazuvious";
AtlasLoot_TableNames["NAXGothiktheHarvester"][1] = "NAXGothiktheHarvester";
AtlasLoot_TableNames["NAXTheFourHorsemen"][1] = "NAXTheFourHorsemen";
AtlasLoot_TableNames["NAXNoththePlaguebringer"][1] = "NAXNoththePlaguebringer";
AtlasLoot_TableNames["NAXHeigantheUnclean"][1] = "NAXHeigantheUnclean";
AtlasLoot_TableNames["NAXLoatheb"][1] = "NAXLoatheb";
AtlasLoot_TableNames["NAXSapphiron"][1] = "NAXSapphiron";
AtlasLoot_TableNames["NAXKelThuzard"][1] = "NAXKelThuzard";
AtlasLoot_TableNames["NAXTrash"][1] = "NAXTrash";
	--Onyxia's Lair
AtlasLoot_TableNames["Onyxia"][1] = "Onyxia";
	--Ragefire Chasm
AtlasLoot_TableNames["RFCBazzalan"][1] = "RFCBazzalan";
AtlasLoot_TableNames["RFCOggleflint"][1] = "RFCOggleflint";
AtlasLoot_TableNames["RFCTaragaman"][1] = "RFCTaragaman";
AtlasLoot_TableNames["RFCJergosh"][1] = "RFCJergosh";
	--Razorfen Downs
AtlasLoot_TableNames["RFDTutenkash"][1] = "RFDTutenkash";
AtlasLoot_TableNames["RFDHenryStern"][1] = "RFDHenryStern";
AtlasLoot_TableNames["RFDLadyF"][1] = "RFDLadyF";
AtlasLoot_TableNames["RFDMordreshFireEye"][1] = "RFDMordreshFireEye";
AtlasLoot_TableNames["RFDGlutton"][1] = "RFDGlutton";
AtlasLoot_TableNames["RFDRagglesnout"][1] = "RFDRagglesnout";
AtlasLoot_TableNames["RFDAmnennar"][1] = "RFDAmnennar";
AtlasLoot_TableNames["RFDPlaguemaw"][1] = "RFDPlaguemaw";
AtlasLoot_TableNames["RFDTrash"][1] = "RFDTrash";
	--Razorfen Kraul
AtlasLoot_TableNames["RFKAggem"][1] = "RFKAggem";
AtlasLoot_TableNames["RFKDeathSpeakerJargba"][1] = "RFKDeathSpeakerJargba";
AtlasLoot_TableNames["RFKRazorfenSpearhide"][1] = "RFKRazorfenSpearhide";
AtlasLoot_TableNames["RFKOverlordRamtusk"][1] = "RFKOverlordRamtusk";
AtlasLoot_TableNames["RFKAgathelos"][1] = "RFKAgathelos";
AtlasLoot_TableNames["RFKBlindHunter"][1] = "RFKBlindHunter";
AtlasLoot_TableNames["RFKCharlgaRazorflank"][1] = "RFKCharlgaRazorflank";
AtlasLoot_TableNames["RFKEarthcallerHalmgar"][1] = "RFKEarthcallerHalmgar";
AtlasLoot_TableNames["RFKRoogug"][1] = "RFKRoogug";
AtlasLoot_TableNames["RFKTrash"][1] = "RFKTrash";
	--The Ruins of Ahn'Qiraj
AtlasLoot_TableNames["AQ20Kurinnaxx"][1] = "AQ20Kurinnaxx";
AtlasLoot_TableNames["AQ20Andorov"][1] = "AQ20Andorov";
AtlasLoot_TableNames["AQ20CAPTAIN"][1] = "AQ20CAPTAIN";
AtlasLoot_TableNames["AQ20Rajaxx"][1] = "AQ20Rajaxx";
AtlasLoot_TableNames["AQ20Moam"][1] = "AQ20Moam";
AtlasLoot_TableNames["AQ20Buru"][1] = "AQ20Buru";
AtlasLoot_TableNames["AQ20Ayamiss"][1] = "AQ20Ayamiss";
AtlasLoot_TableNames["AQ20Ossirian"][1] = "AQ20Ossirian";
AtlasLoot_TableNames["AQ20Trash"][1] = "AQ20Trash";
AtlasLoot_TableNames["AQ20ClassBooks"][1] = "AQ20ClassBooks";
AtlasLoot_TableNames["AQ20Enchants"][1] = "AQ20Enchants";
	--Scarlet Monestery - Armory
AtlasLoot_TableNames["SMHerod"][1] = "SMHerod";
AtlasLoot_TableNames["SMQuartermaster"][1] = "SMQuartermaster";
AtlasLoot_TableNames["SMATrash"][1] = "SMATrash";
	--Scarlet Monestery - Cathedral
AtlasLoot_TableNames["SMFairbanks"][1] = "SMFairbanks";
AtlasLoot_TableNames["SMMograine"][1] = "SMMograine";
AtlasLoot_TableNames["SMWhitemane"][1] = "SMWhitemane";
AtlasLoot_TableNames["SMCTrash"][1] = "SMCTrash";
	--Scarlet Monestery - Graveyard
AtlasLoot_TableNames["SMVishas"][1] = "SMVishas";
AtlasLoot_TableNames["SMDukeDreadmoore"][1] = "SMDukeDreadmoore";
AtlasLoot_TableNames["SMScorn"][1] = "SMScorn";
AtlasLoot_TableNames["SMIronspine"][1] = "SMIronspine";
AtlasLoot_TableNames["SMAzshir"][1] = "SMAzshir";
AtlasLoot_TableNames["SMFallenChampion"][1] = "SMFallenChampion";
AtlasLoot_TableNames["SMBloodmageThalnos"][1] = "SMBloodmageThalnos";
AtlasLoot_TableNames["SMGTrash"][1] = "SMGTrash";
	--Scarlet Monestery - Library
AtlasLoot_TableNames["SMHoundmasterLoksey"][1] = "SMHoundmasterLoksey";
AtlasLoot_TableNames["SMBrotherWystan"][1] = "SMBrotherWystan";
AtlasLoot_TableNames["SMDoan"][1] = "SMDoan";
AtlasLoot_TableNames["SMDoansBox"][1] = "SMDoansBox";
AtlasLoot_TableNames["SMLTrash"][1] = "SMLTrash";
	--Scholomance
AtlasLoot_TableNames["SCHOLOBlood"][1] = "SCHOLOBlood";
AtlasLoot_TableNames["SCHOLOKirtonostheHerald"][1] = "SCHOLOKirtonostheHerald";
AtlasLoot_TableNames["SCHOLOJandiceBarov"][1] = "SCHOLOJandiceBarov";
AtlasLoot_TableNames["SCHOLOLordBlackwood"][1] = "SCHOLOLordBlackwood";
AtlasLoot_TableNames["SCHOLORattlegore"][1] = "SCHOLORattlegore";
AtlasLoot_TableNames["SCHOLODeathKnight"][1] = "SCHOLODeathKnight";
AtlasLoot_TableNames["SCHOLOMarduk"][1] = "SCHOLOMarduk";
AtlasLoot_TableNames["SCHOLOVectus"][1] = "SCHOLOVectus";
AtlasLoot_TableNames["SCHOLORasFrostwhisper"][1] = "SCHOLORasFrostwhisper";
AtlasLoot_TableNames["SCHOLOKormok"][1] = "SCHOLOKormok";
AtlasLoot_TableNames["SCHOLOInstructorMalicia"][1] = "SCHOLOInstructorMalicia";
AtlasLoot_TableNames["SCHOLODoctorTheolenKrastinov"][1] = "SCHOLODoctorTheolenKrastinov";
AtlasLoot_TableNames["SCHOLOLorekeeperPolkelt"][1] = "SCHOLOLorekeeperPolkelt";
AtlasLoot_TableNames["SCHOLOTheRavenian"][1] = "SCHOLOTheRavenian";
AtlasLoot_TableNames["SCHOLOLordAlexeiBarov"][1] = "SCHOLOLordAlexeiBarov";
AtlasLoot_TableNames["SCHOLOLadyIlluciaBarov"][1] = "SCHOLOLadyIlluciaBarov";
AtlasLoot_TableNames["SCHOLODarkmasterGandling"][1] = "SCHOLODarkmasterGandling";
AtlasLoot_TableNames["SCHOLOTrash"][1] = "SCHOLOTrash";
	--Shadowfang Keep
AtlasLoot_TableNames["SFKRethilgore"][1] = "SFKRethilgore";
AtlasLoot_TableNames["SFKFelSteed"][1] = "SFKFelSteed";
AtlasLoot_TableNames["SFKJordansHammer"][1] = "SFKJordansHammer";
AtlasLoot_TableNames["SFKRazorclawtheButcher"][1] = "SFKRazorclawtheButcher";
AtlasLoot_TableNames["SFKSilverlaine"][1] = "SFKSilverlaine";
AtlasLoot_TableNames["SFKSpringvale"][1] = "SFKSpringvale";
AtlasLoot_TableNames["SFKSever"][1] = "SFKSever";
AtlasLoot_TableNames["SFKOdotheBlindwatcher"][1] = "SFKOdotheBlindwatcher";
AtlasLoot_TableNames["SFKFenrustheDevourer"][1] = "SFKFenrustheDevourer";
AtlasLoot_TableNames["SFKBookofUr"][1] = "SFKBookofUr";
AtlasLoot_TableNames["SFKArugalsVoidwalker"][1] = "SFKArugalsVoidwalker";
AtlasLoot_TableNames["SFKWolfMasterNandos"][1] = "SFKWolfMasterNandos";
AtlasLoot_TableNames["SFKArchmageArugal"][1] = "SFKArchmageArugal";
AtlasLoot_TableNames["SFKDeathswornCaptain"][1] = "SFKDeathswornCaptain";
AtlasLoot_TableNames["SFKPrelate"][1] = "SFKPrelate";
AtlasLoot_TableNames["SFKTrash"][1] = "SFKTrash";
	--The Stockade
AtlasLoot_TableNames["SWStTargorr"][1] = "SWStTargorr";
AtlasLoot_TableNames["SWStKamDeepfury"][1] = "SWStKamDeepfury";
AtlasLoot_TableNames["SWStHamhock"][1] = "SWStHamhock";
AtlasLoot_TableNames["SWStDextren"][1] = "SWStDextren";
AtlasLoot_TableNames["SWStBazil"][1] = "SWStBazil";
AtlasLoot_TableNames["SWStBruegalIronknuckle"][1] = "SWStBruegalIronknuckle";
AtlasLoot_TableNames["SWStTrash"][1] = "SWStTrash";
	--Stratholme
AtlasLoot_TableNames["STRATSkull"][1] = "STRATSkull";
AtlasLoot_TableNames["STRATStratholmeCourier"][1] = "STRATStratholmeCourier";
AtlasLoot_TableNames["STRATPostmaster"][1] = "STRATPostmaster";
AtlasLoot_TableNames["STRATFrasSiabi"][1] = "STRATFrasSiabi";
AtlasLoot_TableNames["STRATAtiesh"][1] = "STRATAtiesh";
AtlasLoot_TableNames["STRATBalzaphon"][1] = "STRATBalzaphon";
AtlasLoot_TableNames["STRATHearthsingerForresten"][1] = "STRATHearthsingerForresten";
AtlasLoot_TableNames["STRATTheUnforgiven"][1] = "STRATTheUnforgiven";
AtlasLoot_TableNames["STRATTimmytheCruel"][1] = "STRATTimmytheCruel";
AtlasLoot_TableNames["STRATMalor"][1] = "STRATMalor";
AtlasLoot_TableNames["STRATMalorsStrongbox"][1] = "STRATMalorsStrongbox";
AtlasLoot_TableNames["STRATCrimsonHammersmith"][1] = "STRATCrimsonHammersmith";
AtlasLoot_TableNames["STRATBSPlansSerenity"][1] = "STRATBSPlansSerenity";
AtlasLoot_TableNames["STRATCannonMasterWilley"][1] = "STRATCannonMasterWilley";
AtlasLoot_TableNames["STRATArchivistGalford"][1] = "STRATArchivistGalford";
AtlasLoot_TableNames["STRATBalnazzar"][1] = "STRATBalnazzar";
AtlasLoot_TableNames["STRATSothosJarien"][1] = "STRATSothosJarien";
AtlasLoot_TableNames["STRATStonespine"][1] = "STRATStonespine";
AtlasLoot_TableNames["STRATNerubenkan"][1] = "STRATNerubenkan";
AtlasLoot_TableNames["STRATBaronessAnastari"][1] = "STRATBaronessAnastari";
AtlasLoot_TableNames["STRATBlackGuardSwordsmith"][1] = "STRATBlackGuardSwordsmith";
AtlasLoot_TableNames["STRATBSPlansCorruption"][1] = "STRATBSPlansCorruption";
AtlasLoot_TableNames["STRATMalekithePallid"][1] = "STRATMalekithePallid";
AtlasLoot_TableNames["STRATMagistrateBarthilas"][1] = "STRATMagistrateBarthilas";
AtlasLoot_TableNames["STRATRamsteintheGorger"][1] = "STRATRamsteintheGorger";
AtlasLoot_TableNames["STRATBaronRivendare"][1] = "STRATBaronRivendare";
AtlasLoot_TableNames["STRATTrash"][1] = "STRATTrash";
	--Sunken Temple
AtlasLoot_TableNames["STSpawnOfHakkar"][1] = "STSpawnOfHakkar";
AtlasLoot_TableNames["STBalconyMinibosses"][1] = "STBalconyMinibosses";
AtlasLoot_TableNames["STAtalalarion"][1] = "STAtalalarion";
AtlasLoot_TableNames["STDreamscythe"][1] = "STDreamscythe";
AtlasLoot_TableNames["STWeaver"][1] = "STWeaver";
AtlasLoot_TableNames["STAvatarofHakkar"][1] = "STAvatarofHakkar";
AtlasLoot_TableNames["STJammalan"][1] = "STJammalan";
AtlasLoot_TableNames["STOgom"][1] = "STOgom";
AtlasLoot_TableNames["STMorphaz"][1] = "STMorphaz";
AtlasLoot_TableNames["STHazzas"][1] = "STHazzas";
AtlasLoot_TableNames["STEranikus"][1] = "STEranikus";
AtlasLoot_TableNames["STTrash"][1] = "STTrash";
	-- Hateforge Quarry
AtlasLoot_TableNames["HQHighForemanBargulBlackhammer"][1] = "HQHighForemanBargulBlackhammer";
AtlasLoot_TableNames["HQEngineerFiggles"][1] = "HQEngineerFiggles";
AtlasLoot_TableNames["HQCorrosis"][1] = "HQCorrosis";
AtlasLoot_TableNames["HQHatereaverAnnihilator"][1] = "HQHatereaverAnnihilator";
AtlasLoot_TableNames["HQHargeshDoomcaller"][1] = "HQHargeshDoomcaller";
AtlasLoot_TableNames["HQTrash"][1] = "HQTrash";
	-- The Cresant Grove
AtlasLoot_TableNames["TCGGrovetenderEngryss"][1] = "TCGGrovetenderEngryss";
AtlasLoot_TableNames["TCGKeeperRanathos"][1] = "TCGKeeperRanathos";
AtlasLoot_TableNames["TCGHighPriestessAlathea"][1] = "TCGHighPriestessAlathea";
AtlasLoot_TableNames["TCGFenektistheDeceiver"][1] = "TCGFenektistheDeceiver";
AtlasLoot_TableNames["TCGMasterRaxxieth"][1] = "TCGMasterRaxxieth";
AtlasLoot_TableNames["TCGTrash"][1] = "TCGTrash";
	-- Karazhan Crypt
AtlasLoot_TableNames["KCMarrowspike"][1] = "KCMarrowspike";
AtlasLoot_TableNames["KCHivaxxis"][1] = "KCHivaxxis";
AtlasLoot_TableNames["KCCorpsemuncher"][1] = "KCCorpsemuncher";
AtlasLoot_TableNames["KCGuardCaptainGort"][1] = "KCGuardCaptainGort";
AtlasLoot_TableNames["KCArchlichEnkhraz"][1] = "KCArchlichEnkhraz";
AtlasLoot_TableNames["KCCommanderAndreon"][1] = "KCCommanderAndreon";
AtlasLoot_TableNames["KCAlarus"][1] = "KCAlarus";
AtlasLoot_TableNames["KCTreasure"][1] = "KCTreasure";
AtlasLoot_TableNames["KCTrash"][1] = "KCTrash";
	-- Caverns of Time: Black Morass
AtlasLoot_TableNames["COTBMChronar"][1] = "COTBMChronar";
AtlasLoot_TableNames["COTBMEpidamu"][1] = "COTBMEpidamu";
AtlasLoot_TableNames["COTBMDriftingAvatar"][1] = "COTBMDriftingAvatar";
AtlasLoot_TableNames["COTBMTimeLordEpochronos"][1] = "COTBMTimeLordEpochronos";
AtlasLoot_TableNames["COTBMMossheart"][1] = "COTBMMossheart";
AtlasLoot_TableNames["COTBMRotmaw"][1] = "COTBMRotmaw";
AtlasLoot_TableNames["COTBMAntnormi"][1] = "COTBMAntnormi";
AtlasLoot_TableNames["COTTrash"][1] = "COTTrash";
AtlasLoot_TableNames["COTBMInfiniteChromie"][1] = "COTBMInfiniteChromie";
	-- Stormwind Vault
AtlasLoot_TableNames["SWVAszoshGrimflame"][1] = "SWVAszoshGrimflame";
AtlasLoot_TableNames["SWVThamGrarr"][1] = "SWVThamGrarr";
AtlasLoot_TableNames["SWVBlackBride"][1] = "SWVBlackBride";
AtlasLoot_TableNames["SWVDamian"][1] = "SWVDamian";
AtlasLoot_TableNames["SWVVolkanCruelblade"][1] = "SWVVolkanCruelblade";
AtlasLoot_TableNames["SWVVaultArmoryEquipment"][1] = "SWVVaultArmoryEquipment";
AtlasLoot_TableNames["SWVTrash"][1] = "SWVTrash";
	--Temple of Ahn'Qiraj
AtlasLoot_TableNames["AQ40Skeram"][1] = "AQ40Skeram";
AtlasLoot_TableNames["AQ40Trio"][1] = "AQ40Trio";
AtlasLoot_TableNames["AQ40Sartura"][1] = "AQ40Sartura";
AtlasLoot_TableNames["AQ40Fankriss"][1] = "AQ40Fankriss";
AtlasLoot_TableNames["AQ40Viscidus"][1] = "AQ40Viscidus";
AtlasLoot_TableNames["AQ40Huhuran"][1] = "AQ40Huhuran";
AtlasLoot_TableNames["AQ40Emperors"][1] = "AQ40Emperors";
AtlasLoot_TableNames["AQ40Ouro"][1] = "AQ40Ouro";
AtlasLoot_TableNames["AQ40CThun"][1] = "AQ40CThun";
AtlasLoot_TableNames["AQ40Trash1"][1] = "AQ40Trash1";
AtlasLoot_TableNames["AQ40Trash2"][1] = "AQ40Trash2";
AtlasLoot_TableNames["AQOpening"][1] = "AQOpening";
AtlasLoot_TableNames["AQEnchants"][1] = "AQEnchants";
	--Uldaman
AtlasLoot_TableNames["UldMagreganDeepshadow"][1] = "UldMagreganDeepshadow";
AtlasLoot_TableNames["UldTabletofRyuneh"][1] = "UldTabletofRyuneh";
AtlasLoot_TableNames["UldKromStoutarmChest"][1] = "UldKromStoutarmChest";
AtlasLoot_TableNames["UldGarrettFamilyChest"][1] = "UldGarrettFamilyChest";
AtlasLoot_TableNames["UldShovelphlange"][1] = "UldShovelphlange";
AtlasLoot_TableNames["UldRevelosh"][1] = "UldRevelosh";
AtlasLoot_TableNames["UldEric"][1] = "UldEric";
AtlasLoot_TableNames["UldOlaf"][1] = "UldOlaf";
AtlasLoot_TableNames["UldBaelog"][1] = "UldBaelog";
AtlasLoot_TableNames["UldBaelogsChest"][1] = "UldBaelogsChest";
AtlasLoot_TableNames["UldIronaya"][1] = "UldIronaya";
AtlasLoot_TableNames["UldObsidianSentinel"][1] = "UldObsidianSentinel";
AtlasLoot_TableNames["UldAncientStoneKeeper"][1] = "UldAncientStoneKeeper";
AtlasLoot_TableNames["UldGalgannFirehammer"][1] = "UldGalgannFirehammer";
AtlasLoot_TableNames["UldTabletofWill"][1] = "UldTabletofWill";
AtlasLoot_TableNames["UldShadowforgeCache"][1] = "UldShadowforgeCache";
AtlasLoot_TableNames["UldGrimlok"][1] = "UldGrimlok";
AtlasLoot_TableNames["UldArchaedas"][1] = "UldArchaedas";
AtlasLoot_TableNames["UldTrash"][1] = "UldTrash";
	--Gilneas City
AtlasLoot_TableNames["GCMatthiasHoltz"][1] = "GCMatthiasHoltz";
AtlasLoot_TableNames["GCPackmasterRagetooth"][1] = "GCPackmasterRagetooth";
AtlasLoot_TableNames["GCJudgeSutherland"][1] = "GCJudgeSutherland";
AtlasLoot_TableNames["GCDustivanBlackcowl"][1] = "GCDustivanBlackcowl";
AtlasLoot_TableNames["GCMarshalMagnusGreystone"][1] = "GCMarshalMagnusGreystone";
AtlasLoot_TableNames["GCHorsemasterLevvin"][1] = "GCHorsemasterLevvin";
AtlasLoot_TableNames["GCHarlowFamilyChest"][1] = "GCHarlowFamilyChest";
AtlasLoot_TableNames["GCGennGreymane"][1] = "GCGennGreymane";
AtlasLoot_TableNames["GCTrash"][1] = "GCTrash";
	--Wailing Caverns
AtlasLoot_TableNames["WCKalldanFelmoon"][1] = "WCKalldanFelmoon";
AtlasLoot_TableNames["WCMadMagglish"][1] = "WCMadMagglish";
AtlasLoot_TableNames["WCTrigoretheLasher"][1] = "WCTrigoretheLasher";
AtlasLoot_TableNames["WCBoahn"][1] = "WCBoahn";
AtlasLoot_TableNames["WCLordCobrahn"][1] = "WCLordCobrahn";
AtlasLoot_TableNames["WCLadyAnacondra"][1] = "WCLadyAnacondra";
AtlasLoot_TableNames["WCKresh"][1] = "WCKresh";
AtlasLoot_TableNames["WCDeviateFaerieDragon"][1] = "WCDeviateFaerieDragon";
AtlasLoot_TableNames["WCZandara"][1] = "WCZandara";
AtlasLoot_TableNames["WCLordPythas"][1] = "WCLordPythas";
AtlasLoot_TableNames["WCSkum"][1] = "WCSkum";
AtlasLoot_TableNames["WCVangros"][1] = "WCVangros";
AtlasLoot_TableNames["WCLordSerpentis"][1] = "WCLordSerpentis";
AtlasLoot_TableNames["WCVerdan"][1] = "WCVerdan";
AtlasLoot_TableNames["WCMutanus"][1] = "WCMutanus";
AtlasLoot_TableNames["WCTrash"][1] = "WCTrash";
	--Zul'Farrak
AtlasLoot_TableNames["ZFAntusul"][1] = "ZFAntusul";
AtlasLoot_TableNames["ZFThekatheMartyr"][1] = "ZFThekatheMartyr";
AtlasLoot_TableNames["ZFWitchDoctorZumrah"][1] = "ZFWitchDoctorZumrah";
AtlasLoot_TableNames["ZFNekrumGutchewer"][1] = "ZFNekrumGutchewer";
AtlasLoot_TableNames["ZFSezzziz"][1] = "ZFSezzziz";
AtlasLoot_TableNames["ZFDustwraith"][1] = "ZFDustwraith";
AtlasLoot_TableNames["ZFSergeantBly"][1] = "ZFSergeantBly";
AtlasLoot_TableNames["ZFSandfury"][1] = "ZFSandfury";
AtlasLoot_TableNames["ZFHydromancerVelratha"][1] = "ZFHydromancerVelratha";
AtlasLoot_TableNames["ZFGahzrilla"][1] = "ZFGahzrilla";
AtlasLoot_TableNames["ZFChiefUkorzSandscalp"][1] = "ZFChiefUkorzSandscalp";
AtlasLoot_TableNames["ZFZerillis"][1] = "ZFZerillis";
AtlasLoot_TableNames["ZFTrash"][1] = "ZFTrash";
	--Zul'Gurub
AtlasLoot_TableNames["ZGJeklik"][1] = "ZGJeklik";
AtlasLoot_TableNames["ZGVenoxis"][1] = "ZGVenoxis";
AtlasLoot_TableNames["ZGMarli"][1] = "ZGMarli";
AtlasLoot_TableNames["ZGMandokir"][1] = "ZGMandokir";
AtlasLoot_TableNames["ZGGrilek"][1] = "ZGGrilek";
AtlasLoot_TableNames["ZGHazzarah"][1] = "ZGHazzarah";
AtlasLoot_TableNames["ZGRenataki"][1] = "ZGRenataki";
AtlasLoot_TableNames["ZGWushoolay"][1] = "ZGWushoolay";
AtlasLoot_TableNames["ZGGahzranka"][1] = "ZGGahzranka";
AtlasLoot_TableNames["ZGThekal"][1] = "ZGThekal";
AtlasLoot_TableNames["ZGArlokk"][1] = "ZGArlokk";
AtlasLoot_TableNames["ZGJindo"][1] = "ZGJindo";
AtlasLoot_TableNames["ZGHakkar"][1] = "ZGHakkar";
AtlasLoot_TableNames["ZGMuddyChurningWaters"][1] = "ZGMuddyChurningWaters";
AtlasLoot_TableNames["ZGJinxedHoodooPile"][1] = "ZGJinxedHoodooPile";
AtlasLoot_TableNames["ZGShared"][1] = "ZGShared";
AtlasLoot_TableNames["ZGTrash1"][1] = "ZGTrash1";
AtlasLoot_TableNames["ZGTrash2"][1] = "ZGTrash2";
AtlasLoot_TableNames["ZGEnchants"][1] = "ZGEnchants";
	--Emerald Sanctum
AtlasLoot_TableNames["ESErennius"][1] = "ESErennius";
AtlasLoot_TableNames["ESSolnius1"][1] = "ESSolnius1";
AtlasLoot_TableNames["ESHardMode"][1] = "ESHardMode";
AtlasLoot_TableNames["ESTrash"][1] = "ESTrash";
	--Lower Karazhan Halls
AtlasLoot_TableNames["LKHRolfen"][1] = "LKHRolfen";
AtlasLoot_TableNames["LKHBroodQueenAraxxna"][1] = "LKHBroodQueenAraxxna";
AtlasLoot_TableNames["LKHGrizikil"][1] = "LKHGrizikil";
AtlasLoot_TableNames["LKHClawlordHowlfang"][1] = "LKHClawlordHowlfang";
AtlasLoot_TableNames["LKHLordBlackwaldII"][1] = "LKHLordBlackwaldII";
AtlasLoot_TableNames["LKHMoroes"][1] = "LKHMoroes";
AtlasLoot_TableNames["LKHTrash"][1] = "LKHTrash";
AtlasLoot_TableNames["LKHEnchants"][1] = "LKHEnchants";
    -- Upper Karazhan Halls
AtlasLoot_TableNames["UKHGnarlmoon"][1] = "UKHGnarlmoon";
AtlasLoot_TableNames["UKHIncantagos"][1] = "UKHIncantagos";
AtlasLoot_TableNames["UKHAnomalus"][1] = "UKHAnomalus";
AtlasLoot_TableNames["UKHEcho"][1] = "UKHEcho";
AtlasLoot_TableNames["UKHKing"][1] = "UKHKing";
AtlasLoot_TableNames["UKHSanvTasdal"][1] = "UKHSanvTasdal";
AtlasLoot_TableNames["UKHKruul"][1] = "UKHKruul";
AtlasLoot_TableNames["UKHRupturan"][1] = "UKHRupturan";
AtlasLoot_TableNames["UKHMephistroth"][1] = "UKHMephistroth";
AtlasLoot_TableNames["UKHTrash"][1] = "UKHTrash";
	------------
	--- Sets ---
	------------
	--Vanilla WoW Sets
AtlasLoot_TableNames["DEADMINES"][1] = "DEADMINES";
AtlasLoot_TableNames["WAILING"][1] = "WAILING";
AtlasLoot_TableNames["SCARLET"][1] = "SCARLET";
AtlasLoot_TableNames["BLACKROCKD"][1] = "BLACKROCKD";
AtlasLoot_TableNames["IRONWEAVE"][1] = "IRONWEAVE";
AtlasLoot_TableNames["ScholoCloth"][1] = "ScholoCloth";
AtlasLoot_TableNames["ScholoLeather"][1] = "ScholoLeather";
AtlasLoot_TableNames["ScholoMail"][1] = "ScholoMail";
AtlasLoot_TableNames["ScholoPlate"][1] = "ScholoPlate";
AtlasLoot_TableNames["STRAT"][1] = "STRAT";
AtlasLoot_TableNames["SpiderKiss"][1] = "SpiderKiss";
AtlasLoot_TableNames["DalRend"][1] = "DalRend";
AtlasLoot_TableNames["ZGRings"][1] = "ZGRings";
AtlasLoot_TableNames["ShardOfGods"][1] = "ShardOfGods";
AtlasLoot_TableNames["SpiritofEskhandar"][1] = "SpiritofEskhandar";
AtlasLoot_TableNames["HakkariBlades"][1] = "HakkariBlades";
AtlasLoot_TableNames["PrimalBlessing"][1] = "PrimalBlessing";
AtlasLoot_TableNames["ScourgeInvasion"][1] = "ScourgeInvasion";
AtlasLoot_TableNames["Legendaries"][1] = "Legendaries";
AtlasLoot_TableNames["RareMounts"][1] = "RareMounts";
AtlasLoot_TableNames["PvPMountsSets"][1] = "PvPMountsSets";
AtlasLoot_TableNames["Tabards"][1] = "Tabards";
AtlasLoot_TableNames["RarePets1"][1] = "RarePets1";
AtlasLoot_TableNames["RarePets2"][1] = "RarePets2";
	--Crafted Sets - Blacksmithing
AtlasLoot_TableNames["SteelPlate"][1] = "SteelPlate";
AtlasLoot_TableNames["ImperialPlate"][1] = "ImperialPlate";
AtlasLoot_TableNames["TheDarksoul"][1] = "TheDarksoul";
AtlasLoot_TableNames["BloodsoulEmbrace"][1] = "BloodsoulEmbrace";
	--Crafted Sets - Tailoring
AtlasLoot_TableNames["AugerersAttire"][1] = "AugerersAttire";
AtlasLoot_TableNames["ShadoweaveSet"][1] = "ShadoweaveSet";
AtlasLoot_TableNames["DivinersGarments"][1] = "DivinersGarments";
AtlasLoot_TableNames["PillagersGarb"][1] = "PillagersGarb";
AtlasLoot_TableNames["BloodvineG"][1] = "BloodvineG";
AtlasLoot_TableNames["MoonclothSet"][1] = "MoonclothSet";
	--Crafted Sets - Leatherworking
AtlasLoot_TableNames["GriftersArmor"][1] = "GriftersArmor";
AtlasLoot_TableNames["PrimalistsTrappings"][1] = "PrimalistsTrappings";
AtlasLoot_TableNames["VolcanicArmor"][1] = "VolcanicArmor";
AtlasLoot_TableNames["IronfeatherArmor"][1] = "IronfeatherArmor";
AtlasLoot_TableNames["StormshroudArmor"][1] = "StormshroudArmor";
AtlasLoot_TableNames["DevilsaurArmor"][1] = "DevilsaurArmor";
AtlasLoot_TableNames["BloodTigerH"][1] = "BloodTigerH";
AtlasLoot_TableNames["PrimalBatskin"][1] = "PrimalBatskin";
AtlasLoot_TableNames["RedDragonM"][1] = "RedDragonM";
AtlasLoot_TableNames["GreenDragonM"][1] = "GreenDragonM";
AtlasLoot_TableNames["BlueDragonM"][1] = "BlueDragonM";
AtlasLoot_TableNames["BlackDragonM"][1] = "BlackDragonM";
	--ZG Sets
AtlasLoot_TableNames["ZGDruid"][1] = "ZGDruid";
AtlasLoot_TableNames["ZGHunter"][1] = "ZGHunter";
AtlasLoot_TableNames["ZGMage"][1] = "ZGMage";
AtlasLoot_TableNames["ZGPaladin"][1] = "ZGPaladin";
AtlasLoot_TableNames["ZGPriest"][1] = "ZGPriest";
AtlasLoot_TableNames["ZGRogue"][1] = "ZGRogue";
AtlasLoot_TableNames["ZGShaman"][1] = "ZGShaman";
AtlasLoot_TableNames["ZGWarlock"][1] = "ZGWarlock";
AtlasLoot_TableNames["ZGWarrior"][1] = "ZGWarrior";
	--AQ20 Sets
AtlasLoot_TableNames["AQ20Mage"][1] = "AQ20Mage";
AtlasLoot_TableNames["AQ20Warlock"][1] = "AQ20Warlock";
AtlasLoot_TableNames["AQ20Priest"][1] = "AQ20Priest";
AtlasLoot_TableNames["AQ20Rogue"][1] = "AQ20Rogue";
AtlasLoot_TableNames["AQ20Druid"][1] = "AQ20Druid";
AtlasLoot_TableNames["AQ20Hunter"][1] = "AQ20Hunter";
AtlasLoot_TableNames["AQ20Paladin"][1] = "AQ20Paladin";
AtlasLoot_TableNames["AQ20Shaman"][1] = "AQ20Shaman";
AtlasLoot_TableNames["AQ20Warrior"][1] = "AQ20Warrior";
	--AQ40 Sets
AtlasLoot_TableNames["AQ40Mage"][1] = "AQ40Mage";
AtlasLoot_TableNames["AQ40Priest"][1] = "AQ40Priest";
AtlasLoot_TableNames["AQ40Warlock"][1] = "AQ40Warlock";
AtlasLoot_TableNames["AQ40Rogue"][1] = "AQ40Rogue";
AtlasLoot_TableNames["AQ40Druid"][1] = "AQ40Druid";
AtlasLoot_TableNames["AQ40Shaman"][1] = "AQ40Shaman";
AtlasLoot_TableNames["AQ40Hunter"][1] = "AQ40Hunter";
AtlasLoot_TableNames["AQ40Warrior"][1] = "AQ40Warrior";
AtlasLoot_TableNames["AQ40Paladin"][1] = "AQ40Paladin";
	--Dungeon Set 1/2
AtlasLoot_TableNames["T0Druid"][1] = "T0Druid";
AtlasLoot_TableNames["T0Hunter"][1] = "T0Hunter";
AtlasLoot_TableNames["T0Mage"][1] = "T0Mage";
AtlasLoot_TableNames["T0Paladin"][1] = "T0Paladin";
AtlasLoot_TableNames["T0Priest"][1] = "T0Priest";
AtlasLoot_TableNames["T0Rogue"][1] = "T0Rogue";
AtlasLoot_TableNames["T0Shaman"][1] = "T0Shaman";
AtlasLoot_TableNames["T0Warlock"][1] = "T0Warlock";
AtlasLoot_TableNames["T0Warrior"][1] = "T0Warrior";
	--T1Sets
AtlasLoot_TableNames["T1Druid"][1] = "T1Druid";
AtlasLoot_TableNames["T1Hunter"][1] = "T1Hunter";
AtlasLoot_TableNames["T1Mage"][1] = "T1Mage";
AtlasLoot_TableNames["T1Paladin"][1] = "T1Paladin";
AtlasLoot_TableNames["T1Priest"][1] = "T1Priest";
AtlasLoot_TableNames["T1Rogue"][1] = "T1Rogue";
AtlasLoot_TableNames["T1Shaman"][1] = "T1Shaman";
AtlasLoot_TableNames["T1Warlock"][1] = "T1Warlock";
AtlasLoot_TableNames["T1Warrior"][1] = "T1Warrior";
	--T2Sets
AtlasLoot_TableNames["T2Druid"][1] = "T2Druid";
AtlasLoot_TableNames["T2Hunter"][1] = "T2Hunter";
AtlasLoot_TableNames["T2Mage"][1] = "T2Mage";
AtlasLoot_TableNames["T2Paladin"][1] = "T2Paladin";
AtlasLoot_TableNames["T2Priest"][1] = "T2Priest";
AtlasLoot_TableNames["T2Rogue"][1] = "T2Rogue";
AtlasLoot_TableNames["T2Shaman"][1] = "T2Shaman";
AtlasLoot_TableNames["T2Warlock"][1] = "T2Warlock";
AtlasLoot_TableNames["T2Warrior"][1] = "T2Warrior";
	--T3 Sets
AtlasLoot_TableNames["T3Druid"][1] = "T3Druid";
AtlasLoot_TableNames["T3Hunter"][1] = "T3Hunter";
AtlasLoot_TableNames["T3Mage"][1] = "T3Mage";
AtlasLoot_TableNames["T3Paladin"][1] = "T3Paladin";
AtlasLoot_TableNames["T3Priest"][1] = "T3Priest";
AtlasLoot_TableNames["T3Rogue"][1] = "T3Rogue";
AtlasLoot_TableNames["T3Shaman"][1] = "T3Shaman";
AtlasLoot_TableNames["T3Warlock"][1] = "T3Warlock";
AtlasLoot_TableNames["T3Warrior"][1] = "T3Warrior";
	--T3.5 Sets
AtlasLoot_TableNames["T35Druid"][1] = "T35Druid";
AtlasLoot_TableNames["T35Hunter"][1] = "T35Hunter";
AtlasLoot_TableNames["T35Mage"][1] = "T35Mage";
AtlasLoot_TableNames["T35Paladin"][1] = "T35Paladin";
AtlasLoot_TableNames["T35Priest"][1] = "T35Priest";
AtlasLoot_TableNames["T35Rogue"][1] = "T35Rogue";
AtlasLoot_TableNames["T35Shaman"][1] = "T35Shaman";
AtlasLoot_TableNames["T35Warlock"][1] = "T35Warlock";
AtlasLoot_TableNames["T35Warrior"][1] = "T35Warrior";
	------------------------
	--- Misc Collections ---
	------------------------
AtlasLoot_TableNames["CraftedWeapons1"][1] = "CraftedWeapons1";
AtlasLoot_TableNames["WorldEpics1"][1] = "WorldEpics1";
AtlasLoot_TableNames["WorldEpics2"][1] = "WorldEpics2";
AtlasLoot_TableNames["WorldEpics3"][1] = "WorldEpics3";
	--------------------
	--- World Bosses ---
	--------------------
AtlasLoot_TableNames["AAzuregos"][1] = "AAzuregos";
AtlasLoot_TableNames["ASpiritA"][1] = "ASpiritA";
AtlasLoot_TableNames["Nerubian"][1] = "Nerubian";
AtlasLoot_TableNames["Reaver"][1] = "Reaver";
AtlasLoot_TableNames["Ostarius"][1] = "Ostarius";
AtlasLoot_TableNames["Concavius"][1] = "Concavius";
AtlasLoot_TableNames["CowKing"][1] = "CowKing";
AtlasLoot_TableNames["KKazzak"][1] = "KKazzak";
AtlasLoot_TableNames["DEmeriss"][1] = "DEmeriss";
AtlasLoot_TableNames["DLethon"][1] = "DLethon";
AtlasLoot_TableNames["DTaerar"][1] = "DTaerar";
AtlasLoot_TableNames["DYsondre"][1] = "DYsondre";
AtlasLoot_TableNames["DTrash"][1] = "DTrash";
AtlasLoot_TableNames["Clackora"][1] = "Clackora";
	-------------------
	--- Rare Spawns ---
	-------------------
AtlasLoot_TableNames["Tarangos"][1] = "Tarangos";
AtlasLoot_TableNames["Kargron"][1] = "Kargron";
AtlasLoot_TableNames["Xalvic"][1] = "Xalvic";
AtlasLoot_TableNames["Mallon"][1] = "Mallon";
AtlasLoot_TableNames["Grugthok"][1] = "Grugthok";
AtlasLoot_TableNames["WanderingKnight"][1] = "WanderingKnight";
AtlasLoot_TableNames["CrusaderLarsarius"][1] = "CrusaderLarsarius";
AtlasLoot_TableNames["Zareth"][1] = "Zareth";
AtlasLoot_TableNames["Jalakar"][1] = "Jalakar";
AtlasLoot_TableNames["Ashbeard"][1] = "Ashbeard";
AtlasLoot_TableNames["AdmiralBareanWestwind"][1] = "AdmiralBareanWestwind";
AtlasLoot_TableNames["EarthcallerRezengal"][1] = "EarthcallerRezengal";
AtlasLoot_TableNames["ShadeMage"][1] = "ShadeMage";
AtlasLoot_TableNames["GraypawAlpha"][1] = "GraypawAlpha";
AtlasLoot_TableNames["Blazespark"][1] = "Blazespark";
AtlasLoot_TableNames["WitchDoctorTanzo"][1] = "WitchDoctorTanzo";
AtlasLoot_TableNames["Dawnhowl"][1] = "Dawnhowl";
AtlasLoot_TableNames["MaltimorsPrototype"][1] = "MaltimorsPrototype";
AtlasLoot_TableNames["Bonecruncher"][1] = "Bonecruncher";
AtlasLoot_TableNames["Duskskitter"][1] = "Duskskitter";
AtlasLoot_TableNames["BaronPerenolde"][1] = "BaronPerenolde";
AtlasLoot_TableNames["Embereye"][1] = "Embereye";
AtlasLoot_TableNames["Rukthok"][1] = "Rukthok";
AtlasLoot_TableNames["Ripjaw"][1] = "Ripjaw";
AtlasLoot_TableNames["Aquitus"][1] = "Aquitus";
AtlasLoot_TableNames["FirstbornofArugal"][1] = "FirstbornofArugal";
AtlasLoot_TableNames["Letashaz"][1] = "Letashaz";
AtlasLoot_TableNames["MargontheMighty"][1] = "MargontheMighty";
AtlasLoot_TableNames["Stoneshell"][1] = "Stoneshell";
AtlasLoot_TableNames["HighvaleSilverback"][1] = "HighvaleSilverback";
AtlasLoot_TableNames["Azurebeak"][1] = "Azurebeak";
AtlasLoot_TableNames["BarkskinFisher"][1] = "BarkskinFisher";
AtlasLoot_TableNames["ShadeflayerGoliath"][1] = "ShadeflayerGoliath";
AtlasLoot_TableNames["M0L1Y"][1] = "M0L1Y";
AtlasLoot_TableNames["WidowoftheWoods"][1] = "WidowoftheWoods";
AtlasLoot_TableNames["KinTozo"][1] = "KinTozo";
AtlasLoot_TableNames["ProfessorLysander"][1] = "ProfessorLysander";
	--------------
	--- Events ---
	--------------
AtlasLoot_TableNames["AbyssalTemplars"][1] = "AbyssalTemplars";
AtlasLoot_TableNames["AbyssalDukes"][1] = "AbyssalDukes";
AtlasLoot_TableNames["AbyssalLords"][1] = "AbyssalLords";
AtlasLoot_TableNames["ChildrensWeek"][1] = "ChildrensWeek";
AtlasLoot_TableNames["Halloween1"][1] = "Halloween1";
AtlasLoot_TableNames["Halloween2"][1] = "Halloween2";
AtlasLoot_TableNames["HarvestFestival"][1] = "HarvestFestival";
AtlasLoot_TableNames["LunarFestival1"][1] = "LunarFestival1";
AtlasLoot_TableNames["LunarFestival2"][1] = "LunarFestival2";
AtlasLoot_TableNames["MidsummerFestival"][1] = "MidsummerFestival";
AtlasLoot_TableNames["Noblegarden"][1] = "Noblegarden";
AtlasLoot_TableNames["Valentineday"][1] = "Valentineday";
AtlasLoot_TableNames["Winterviel"][1] = "Winterviel";
AtlasLoot_TableNames["Winterviel1"][1] = "Winterviel1";
AtlasLoot_TableNames["Winterviel2"][1] = "Winterviel2";
AtlasLoot_TableNames["ElementalInvasion"][1] = "ElementalInvasion";
AtlasLoot_TableNames["FishingExtravaganza"][1] = "FishingExtravaganza";
AtlasLoot_TableNames["GurubashiArena"][1] = "GurubashiArena";
AtlasLoot_TableNames["ScourgeInvasionEvent1"][1] = "ScourgeInvasionEvent1";
AtlasLoot_TableNames["ScourgeInvasionEvent2"][1] = "ScourgeInvasionEvent2";
	------------------------
	--- Classic Factions ---
	------------------------
	--Argent Dawn
AtlasLoot_TableNames["Argent1"][1] = "Argent1";
AtlasLoot_TableNames["Argent2"][1] = "Argent2";
AtlasLoot_TableNames["Argent3"][1] = "Argent3";
AtlasLoot_TableNames["Bloodsail1"][1] = "Bloodsail1";
AtlasLoot_TableNames["AQBroodRings"][1] = "AQBroodRings";
AtlasLoot_TableNames["Cenarion1"][1] = "Cenarion1";
AtlasLoot_TableNames["Cenarion2"][1] = "Cenarion2";
AtlasLoot_TableNames["Cenarion3"][1] = "Cenarion3";
AtlasLoot_TableNames["Cenarion4"][1] = "Cenarion4";
AtlasLoot_TableNames["Darkmoon"][1] = "Darkmoon";
AtlasLoot_TableNames["Defilers"][1] = "Defilers";
AtlasLoot_TableNames["Frostwolf1"][1] = "Frostwolf1";
AtlasLoot_TableNames["WaterLords1"][1] = "WaterLords1";
AtlasLoot_TableNames["GelkisClan1"][1] = "GelkisClan1";
AtlasLoot_TableNames["LeagueofArathor"][1] = "LeagueofArathor";
AtlasLoot_TableNames["MagramClan1"][1] = "MagramClan1";
AtlasLoot_TableNames["Stormpike1"][1] = "Stormpike1";
AtlasLoot_TableNames["Thorium1"][1] = "Thorium1";
AtlasLoot_TableNames["Thorium2"][1] = "Thorium2";
AtlasLoot_TableNames["Timbermaw"][1] = "Timbermaw";
AtlasLoot_TableNames["Wardens1"][1] = "Wardens1";
AtlasLoot_TableNames["Wardens2"][1] = "Wardens2";
AtlasLoot_TableNames["Wintersaber1"][1] = "Wintersaber1";
AtlasLoot_TableNames["Zandalar1"][1] = "Zandalar1";
AtlasLoot_TableNames["Zandalar2"][1] = "Zandalar2";
AtlasLoot_TableNames["Helf"][1] = "Helf";
AtlasLoot_TableNames["Helf2"][1] = "Helf2";
AtlasLoot_TableNames["Helf3"][1] = "Helf3";
AtlasLoot_TableNames["Revantusk"][1] = "Revantusk";
AtlasLoot_TableNames["Revantusk2"][1] = "Revantusk2";
AtlasLoot_TableNames["Revantusk3"][1] = "Revantusk3";
AtlasLoot_TableNames["Ironforge"][1] = "Ironforge";
AtlasLoot_TableNames["Darnassus"][1] = "Darnassus";
AtlasLoot_TableNames["Stormwind"][1] = "Stormwind";
AtlasLoot_TableNames["GnomereganExiles"][1] = "GnomereganExiles";
AtlasLoot_TableNames["DarkspearTrolls"][1] = "DarkspearTrolls";
AtlasLoot_TableNames["DurotarLaborUnion"][1] = "DurotarLaborUnion";
AtlasLoot_TableNames["Undercity"][1] = "Undercity";
AtlasLoot_TableNames["Orgrimmar"][1] = "Orgrimmar";
AtlasLoot_TableNames["ThunderBluff"][1] = "ThunderBluff";
AtlasLoot_TableNames["Dalaran"][1] = "Dalaran";
AtlasLoot_TableNames["Wildhammer"][1] = "Wildhammer";
	--------------
	--- Trades ---
	--------------
	--Alchemy
AtlasLoot_TableNames["AlchemyApprentice1"][1] = "AlchemyApprentice1";
AtlasLoot_TableNames["AlchemyJourneyman1"][1] = "AlchemyJourneyman1";
AtlasLoot_TableNames["AlchemyExpert1"][1] = "AlchemyExpert1";
AtlasLoot_TableNames["AlchemyArtisan1"][1] = "AlchemyArtisan1";
AtlasLoot_TableNames["AlchemyArtisan2"][1] = "AlchemyArtisan2";
AtlasLoot_TableNames["AlchemyFlasks1"][1] = "AlchemyFlasks1";
AtlasLoot_TableNames["AlchemyProtectionPots1"][1] = "AlchemyProtectionPots1";
AtlasLoot_TableNames["AlchemyHealingAndMana1"][1] = "AlchemyHealingAndMana1";
AtlasLoot_TableNames["AlchemyTransmutes1"][1] = "AlchemyTransmutes1";
AtlasLoot_TableNames["AlchemyDefensive1"][1] = "AlchemyDefensive1";
AtlasLoot_TableNames["AlchemyOffensive1"][1] = "AlchemyOffensive1";
AtlasLoot_TableNames["AlchemyOther1"][1] = "AlchemyOther1";
	--BlackSmithing
AtlasLoot_TableNames["SmithingApprentice1"][1] = "SmithingApprentice1";
AtlasLoot_TableNames["SmithingJourneyman1"][1] = "SmithingJourneyman1";
AtlasLoot_TableNames["SmithingJourneyman2"][1] = "SmithingJourneyman2";
AtlasLoot_TableNames["SmithingExpert1"][1] = "SmithingExpert1";
AtlasLoot_TableNames["SmithingExpert2"][1] = "SmithingExpert2";
AtlasLoot_TableNames["SmithingExpert3"][1] = "SmithingExpert3";
AtlasLoot_TableNames["SmithingArtisan1"][1] = "SmithingArtisan1";
AtlasLoot_TableNames["SmithingArtisan2"][1] = "SmithingArtisan2";
AtlasLoot_TableNames["SmithingArtisan3"][1] = "SmithingArtisan3";
AtlasLoot_TableNames["SmithingArtisan4"][1] = "SmithingArtisan4";
AtlasLoot_TableNames["Armorsmith1"][1] = "Armorsmith1";
AtlasLoot_TableNames["Weaponsmith1"][1] = "Weaponsmith1";
AtlasLoot_TableNames["Axesmith1"][1] = "Axesmith1";
AtlasLoot_TableNames["Hammersmith1"][1] = "Hammersmith1";
AtlasLoot_TableNames["Swordsmith1"][1] = "Swordsmith1";
AtlasLoot_TableNames["SmithingHelm1"][1] = "SmithingHelm1";
AtlasLoot_TableNames["SmithingShoulders1"][1] = "SmithingShoulders1";
AtlasLoot_TableNames["SmithingChest1"][1] = "SmithingChest1";
AtlasLoot_TableNames["SmithingChest2"][1] = "SmithingChest2";
AtlasLoot_TableNames["SmithingBracers1"][1] = "SmithingBracers1";
AtlasLoot_TableNames["SmithingGloves1"][1] = "SmithingGloves1";
AtlasLoot_TableNames["SmithingBelt1"][1] = "SmithingBelt1";
AtlasLoot_TableNames["SmithingPants1"][1] = "SmithingPants1";
AtlasLoot_TableNames["SmithingBoots1"][1] = "SmithingBoots1";
AtlasLoot_TableNames["SmithingAxes1"][1] = "SmithingAxes1";
AtlasLoot_TableNames["SmithingSwords1"][1] = "SmithingSwords1";
AtlasLoot_TableNames["SmithingMaces1"][1] = "SmithingMaces1";
AtlasLoot_TableNames["SmithingFist1"][1] = "SmithingFist1";
AtlasLoot_TableNames["SmithingDaggers1"][1] = "SmithingDaggers1";
AtlasLoot_TableNames["SmithingMisc1"][1] = "SmithingMisc1";
AtlasLoot_TableNames["SmithingMisc2"][1] = "SmithingMisc2";
AtlasLoot_TableNames["SmithingBuckles1"][1] = "SmithingBuckles1";
	--Enchanting
AtlasLoot_TableNames["EnchantingApprentice1"][1] = "EnchantingApprentice1";
AtlasLoot_TableNames["EnchantingJourneyman1"][1] = "EnchantingJourneyman1";
AtlasLoot_TableNames["EnchantingJourneyman2"][1] = "EnchantingJourneyman2";
AtlasLoot_TableNames["EnchantingExpert1"][1] = "EnchantingExpert1";
AtlasLoot_TableNames["EnchantingExpert2"][1] = "EnchantingExpert2";
AtlasLoot_TableNames["EnchantingArtisan1"][1] = "EnchantingArtisan1";
AtlasLoot_TableNames["EnchantingArtisan2"][1] = "EnchantingArtisan2";
AtlasLoot_TableNames["EnchantingArtisan3"][1] = "EnchantingArtisan3";
AtlasLoot_TableNames["EnchantingCloak1"][1] = "EnchantingCloak1";
AtlasLoot_TableNames["EnchantingChest1"][1] = "EnchantingChest1";
AtlasLoot_TableNames["EnchantingBracer1"][1] = "EnchantingBracer1";
AtlasLoot_TableNames["EnchantingGlove1"][1] = "EnchantingGlove1";
AtlasLoot_TableNames["EnchantingBoots1"][1] = "EnchantingBoots1";
AtlasLoot_TableNames["Enchanting2HWeapon1"][1] = "Enchanting2HWeapon1";
AtlasLoot_TableNames["EnchantingWeapon1"][1] = "EnchantingWeapon1";
AtlasLoot_TableNames["EnchantingShield1"][1] = "EnchantingShield1";
AtlasLoot_TableNames["EnchantingMisc1"][1] = "EnchantingMisc1";
	--Engineering
AtlasLoot_TableNames["EngineeringApprentice1"][1] = "EngineeringApprentice1";
AtlasLoot_TableNames["EngineeringJourneyman1"][1] = "EngineeringJourneyman1";
AtlasLoot_TableNames["EngineeringJourneyman2"][1] = "EngineeringJourneyman2";
AtlasLoot_TableNames["EngineeringExpert1"][1] = "EngineeringExpert1";
AtlasLoot_TableNames["EngineeringExpert2"][1] = "EngineeringExpert2";
AtlasLoot_TableNames["EngineeringArtisan1"][1] = "EngineeringArtisan1";
AtlasLoot_TableNames["EngineeringArtisan2"][1] = "EngineeringArtisan2";
AtlasLoot_TableNames["Gnomish1"][1] = "Gnomish1";
AtlasLoot_TableNames["Goblin1"][1] = "Goblin1";
AtlasLoot_TableNames["EngineeringEquipment1"][1] = "EngineeringEquipment1";
AtlasLoot_TableNames["EngineeringTrinkets1"][1] = "EngineeringTrinkets1";
AtlasLoot_TableNames["EngineeringExplosives1"][1] = "EngineeringExplosives1";
AtlasLoot_TableNames["EngineeringParts1"][1] = "EngineeringParts1";
AtlasLoot_TableNames["EngineeringMisc1"][1] = "EngineeringMisc1";
AtlasLoot_TableNames["EngineeringMisc2"][1] = "EngineeringMisc2";
AtlasLoot_TableNames["EngineeringWeapons1"][1] = "EngineeringWeapons1";
	--Leatherworking
AtlasLoot_TableNames["LeatherApprentice1"][1] = "LeatherApprentice1";
AtlasLoot_TableNames["LeatherJourneyman1"][1] = "LeatherJourneyman1";
AtlasLoot_TableNames["LeatherJourneyman2"][1] = "LeatherJourneyman2";
AtlasLoot_TableNames["LeatherExpert1"][1] = "LeatherExpert1";
AtlasLoot_TableNames["LeatherExpert2"][1] = "LeatherExpert2";
AtlasLoot_TableNames["LeatherArtisan1"][1] = "LeatherArtisan1";
AtlasLoot_TableNames["LeatherArtisan2"][1] = "LeatherArtisan2";
AtlasLoot_TableNames["LeatherArtisan3"][1] = "LeatherArtisan3";
AtlasLoot_TableNames["Dragonscale1"][1] = "Dragonscale1";
AtlasLoot_TableNames["Elemental1"][1] = "Elemental1";
AtlasLoot_TableNames["Tribal1"][1] = "Tribal1";
AtlasLoot_TableNames["LeatherHelm1"][1] = "LeatherHelm1";
AtlasLoot_TableNames["LeatherShoulders1"][1] = "LeatherShoulders1";
AtlasLoot_TableNames["LeatherCloak1"][1] = "LeatherCloak1";
AtlasLoot_TableNames["LeatherChest1"][1] = "LeatherChest1";
AtlasLoot_TableNames["LeatherChest2"][1] = "LeatherChest2";
AtlasLoot_TableNames["LeatherBracers1"][1] = "LeatherBracers1";
AtlasLoot_TableNames["LeatherGloves1"][1] = "LeatherGloves1";
AtlasLoot_TableNames["LeatherGloves2"][1] = "LeatherGloves2";
AtlasLoot_TableNames["LeatherBelt1"][1] = "LeatherBelt1";
AtlasLoot_TableNames["LeatherPants1"][1] = "LeatherPants1";
AtlasLoot_TableNames["LeatherPants2"][1] = "LeatherPants2";
AtlasLoot_TableNames["LeatherBoots1"][1] = "LeatherBoots1";
AtlasLoot_TableNames["LeatherBags1"][1] = "LeatherBags1";
AtlasLoot_TableNames["LeatherMisc1"][1] = "LeatherMisc1";
	--Mining
AtlasLoot_TableNames["Mining1"][1] = "Mining1";
AtlasLoot_TableNames["Smelting1"][1] = "Smelting1";
AtlasLoot_TableNames["Herbalism1"][1] = "Herbalism1";
AtlasLoot_TableNames["Herbalism2"][1] = "Herbalism2";
	--Tailoring
AtlasLoot_TableNames["TailoringApprentice1"][1] = "TailoringApprentice1";
AtlasLoot_TableNames["TailoringApprentice2"][1] = "TailoringApprentice2";
AtlasLoot_TableNames["TailoringJourneyman1"][1] = "TailoringJourneyman1";
AtlasLoot_TableNames["TailoringJourneyman2"][1] = "TailoringJourneyman2";
AtlasLoot_TableNames["TailoringExpert1"][1] = "TailoringExpert1";
AtlasLoot_TableNames["TailoringExpert2"][1] = "TailoringExpert2";
AtlasLoot_TableNames["TailoringArtisan1"][1] = "TailoringArtisan1";
AtlasLoot_TableNames["TailoringArtisan2"][1] = "TailoringArtisan2";
AtlasLoot_TableNames["TailoringArtisan3"][1] = "TailoringArtisan3";
AtlasLoot_TableNames["TailoringArtisan4"][1] = "TailoringArtisan4";
AtlasLoot_TableNames["TailoringArtisan5"][1] = "TailoringArtisan5";
AtlasLoot_TableNames["TailoringHelm1"][1] = "TailoringHelm1";
AtlasLoot_TableNames["TailoringShoulders1"][1] = "TailoringShoulders1";
AtlasLoot_TableNames["TailoringCloak1"][1] = "TailoringCloak1";
AtlasLoot_TableNames["TailoringChest1"][1] = "TailoringChest1";
AtlasLoot_TableNames["TailoringChest2"][1] = "TailoringChest2";
AtlasLoot_TableNames["TailoringBracers1"][1] = "TailoringBracers1";
AtlasLoot_TableNames["TailoringGloves1"][1] = "TailoringGloves1";
AtlasLoot_TableNames["TailoringBelt1"][1] = "TailoringBelt1";
AtlasLoot_TableNames["TailoringPants1"][1] = "TailoringPants1";
AtlasLoot_TableNames["TailoringBoots1"][1] = "TailoringBoots1";
AtlasLoot_TableNames["TailoringBags1"][1] = "TailoringBags1";
AtlasLoot_TableNames["TailoringShirt1"][1] = "TailoringShirt1";
AtlasLoot_TableNames["TailoringMisc1"][1] = "TailoringMisc1";
	--Jewelcrafting
AtlasLoot_TableNames["JewelcraftingApprentice1"][1] = "JewelcraftingApprentice1";
AtlasLoot_TableNames["JewelcraftingJourneyman1"][1] = "JewelcraftingJourneyman1";
AtlasLoot_TableNames["JewelcraftingJourneyman2"][1] = "JewelcraftingJourneyman2";
AtlasLoot_TableNames["JewelcraftingExpert1"][1] = "JewelcraftingExpert1";
AtlasLoot_TableNames["JewelcraftingExpert2"][1] = "JewelcraftingExpert2";
AtlasLoot_TableNames["JewelcraftingExpert3"][1] = "JewelcraftingExpert3";
AtlasLoot_TableNames["JewelcraftingArtisan1"][1] = "JewelcraftingArtisan1";
AtlasLoot_TableNames["JewelcraftingArtisan2"][1] = "JewelcraftingArtisan2";
AtlasLoot_TableNames["JewelcraftingArtisan3"][1] = "JewelcraftingArtisan3";
AtlasLoot_TableNames["JewelcraftingGemstones1"][1] = "JewelcraftingGemstones1";
AtlasLoot_TableNames["JewelcraftingRings1"][1] = "JewelcraftingRings1";
AtlasLoot_TableNames["JewelcraftingRings2"][1] = "JewelcraftingRings2";
AtlasLoot_TableNames["JewelcraftingAmulets1"][1] = "JewelcraftingAmulets1";
AtlasLoot_TableNames["JewelcraftingHelm1"][1] = "JewelcraftingHelm1";
AtlasLoot_TableNames["JewelcraftingBracers1"][1] = "JewelcraftingBracers1";
AtlasLoot_TableNames["JewelcraftingOffHands1"][1] = "JewelcraftingOffHands1";
AtlasLoot_TableNames["JewelcraftingStaves1"][1] = "JewelcraftingStaves1";
AtlasLoot_TableNames["JewelcraftingTrinkets1"][1] = "JewelcraftingTrinkets1";
AtlasLoot_TableNames["JewelcraftingMisc1"][1] = "JewelcraftingMisc1";
AtlasLoot_TableNames["JewelcraftingGemology1"][1] = "JewelcraftingGemology1";
AtlasLoot_TableNames["JewelcraftingGoldsmithing1"][1] = "JewelcraftingGoldsmithing1";
	--Cooking
AtlasLoot_TableNames["CookingApprentice1"][1] = "CookingApprentice1";
AtlasLoot_TableNames["CookingJourneyman1"][1] = "CookingJourneyman1";
AtlasLoot_TableNames["CookingExpert1"][1] = "CookingExpert1";
AtlasLoot_TableNames["CookingArtisan1"][1] = "CookingArtisan1";
	--FirstAid
AtlasLoot_TableNames["FirstAid1"][1] = "FirstAid1";
	--Survival
AtlasLoot_TableNames["Survival1"][1] = "Survival1";
AtlasLoot_TableNames["Survival2"][1] = "Survival2";
	--Poisons
AtlasLoot_TableNames["Poisons1"][1] = "Poisons1";
	-----------
	--- PvP ---
	-----------
	--Blood Ring
AtlasLoot_TableNames["BRRepFriendly"][1] = "BRRepFriendly";
AtlasLoot_TableNames["BRRepHonored"][1] = "BRRepHonored";
AtlasLoot_TableNames["BRRepRevered"][1] = "BRRepRevered";
AtlasLoot_TableNames["BRRepExalted"][1] = "BRRepExalted";
AtlasLoot_TableNames["BRRepTokens"][1] = "BRRepTokens";
	--Alterac Valley
AtlasLoot_TableNames["AVRepFriendly"][1] = "AVRepFriendly";
AtlasLoot_TableNames["AVRepHonored"][1] = "AVRepHonored";
AtlasLoot_TableNames["AVRepRevered"][1] = "AVRepRevered";
AtlasLoot_TableNames["AVRepExalted"][1] = "AVRepExalted";
AtlasLoot_TableNames["AVKorrak"][1] = "AVKorrak";
AtlasLoot_TableNames["AVLokholarIvus"][1] = "AVLokholarIvus";
	--Arathi Basin
AtlasLoot_TableNames["ABRepFriendly"][1] = "ABRepFriendly";
AtlasLoot_TableNames["ABRepHonored2029"][1] = "ABRepHonored2029";
AtlasLoot_TableNames["ABRepHonored3039"][1] = "ABRepHonored3039";
AtlasLoot_TableNames["ABRepHonored4049"][1] = "ABRepHonored4049";
AtlasLoot_TableNames["ABRepHonored5059"][1] = "ABRepHonored5059";
AtlasLoot_TableNames["ABRepRevered2029"][1] = "ABRepRevered2029";
AtlasLoot_TableNames["ABRepRevered3039"][1] = "ABRepRevered3039";
AtlasLoot_TableNames["ABRepRevered4049"][1] = "ABRepRevered4049";
AtlasLoot_TableNames["ABRepRevered5059"][1] = "ABRepRevered5059";
AtlasLoot_TableNames["ABRepExalted"][1] = "ABRepExalted";
	--Warsong Gulch
AtlasLoot_TableNames["WSGRepFriendly"][1] = "WSGRepFriendly";
AtlasLoot_TableNames["WSGRepHonored1019"][1] = "WSGRepHonored1019";
AtlasLoot_TableNames["WSGRepHonored2029"][1] = "WSGRepHonored2029";
AtlasLoot_TableNames["WSGRepHonored3039"][1] = "WSGRepHonored3039";
AtlasLoot_TableNames["WSGRepHonored4049"][1] = "WSGRepHonored4049";
AtlasLoot_TableNames["WSGRepHonored5059"][1] = "WSGRepHonored5059";
AtlasLoot_TableNames["WSGRepRevered1019"][1] = "WSGRepRevered1019";
AtlasLoot_TableNames["WSGRepRevered2029"][1] = "WSGRepRevered2029";
AtlasLoot_TableNames["WSGRepRevered3039"][1] = "WSGRepRevered3039";
AtlasLoot_TableNames["WSGRepRevered4049"][1] = "WSGRepRevered4049";
AtlasLoot_TableNames["WSGRepRevered5059"][1] = "WSGRepRevered5059";
AtlasLoot_TableNames["WSGRepExalted4049"][1] = "WSGRepExalted4049";
AtlasLoot_TableNames["WSGRepExalted5059"][1] = "WSGRepExalted5059";
AtlasLoot_TableNames["WSGRepExalted60"][1] = "WSGRepExalted60";
	--Misc Other PvP
AtlasLoot_TableNames["PvP60Accessories1"][1] = "PvP60Accessories1";
AtlasLoot_TableNames["PvP60Accessories2"][1] = "PvP60Accessories2";
AtlasLoot_TableNames["PvP60Accessories3"][1] = "PvP60Accessories3";
AtlasLoot_TableNames["PVPWeapons1"][1] = "PVPWeapons1";
AtlasLoot_TableNames["PVPWeapons2"][1] = "PVPWeapons2";
AtlasLoot_TableNames["PvPMountsPvP"][1] = "PvPMountsPvP";
	--Level 60 PvP Sets
AtlasLoot_TableNames["PVPDruid"][1] = "PVPDruid";
AtlasLoot_TableNames["PVPHunter"][1] = "PVPHunter";
AtlasLoot_TableNames["PVPMage"][1] = "PVPMage";
AtlasLoot_TableNames["PVPPaladin"][1] = "PVPPaladin";
AtlasLoot_TableNames["PVPPriest"][1] = "PVPPriest";
AtlasLoot_TableNames["PVPRogue"][1] = "PVPRogue";
AtlasLoot_TableNames["PVPShaman"][1] = "PVPShaman";
AtlasLoot_TableNames["PVPWarlock"][1] = "PVPWarlock";
AtlasLoot_TableNames["PVPWarrior"][1] = "PVPWarrior";

AtlasLoot_TableNames["WishList"][1] = "WishList";

end
